
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 109403521
 */
public class AddOrderJFrame extends javax.swing.JFrame {
    
    SetMeal o1 = new SetMeal();
    SingleMeal o2 = new SingleMeal();
    Voucher v = new Voucher();
    
    int FormID;

    DefaultTableModel model;
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    
    public AddOrderJFrame()
    {
        initComponents();
        
        FormID = o1.addForm();
        jLabel5.setText(String.valueOf(FormID));
        
        //jTable1.setRowHeight(40);//設定行高
        
        model = (DefaultTableModel) jTable1.getModel();
        
        //#####################align center and width################################################
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        //jTable1.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        //jTable1.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        jTable1.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        //jTable1.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(260);
        //##################################################################################
        jComboBoxSetID.setModel(new DefaultComboBoxModel<>(o1.getSetType()));
        jComboBoxSetMain.setModel(new DefaultComboBoxModel<>(o2.getMealType("主餐")));
        
        jComboBoxSingle.setModel(new DefaultComboBoxModel<>(o2.getMealType("ALL")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBoxSetID = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonSetAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxSingle = new javax.swing.JComboBox<>();
        jButtonSingleAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxSetMain = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("新增訂單");

        jComboBoxSetID.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jComboBoxSetID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSetIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jLabel2.setText("套餐：");

        jButtonSetAdd.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jButtonSetAdd.setText("新增");
        jButtonSetAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSetAddMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jLabel3.setText("單點：");

        jComboBoxSingle.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jComboBoxSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSingleActionPerformed(evt);
            }
        });

        jButtonSingleAdd.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jButtonSingleAdd.setText("新增");
        jButtonSingleAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSingleAddMouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "方案名稱", "餐點名稱", "價格", "備註"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBoxSetMain.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jComboBoxSetMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSetMainActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jLabel4.setText("訂單編號：");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jLabel5.setToolTipText("");

        jButtonSubmit.setBackground(new java.awt.Color(170, 207, 82));
        jButtonSubmit.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButtonSubmit.setText("結帳");
        jButtonSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubmitMouseClicked(evt);
            }
        });

        jButtonDel.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButtonDel.setText("刪除餐點");
        jButtonDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDelMouseClicked(evt);
            }
        });

        jButtonEdit.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButtonEdit.setText("修改餐點");
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addGap(156, 156, 156)
                                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSetID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSetMain, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSetAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSingleAdd)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSetID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonSetAdd)
                    .addComponent(jComboBoxSingle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonSingleAdd)
                    .addComponent(jComboBoxSetMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSetIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSetIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSetIDActionPerformed

    private void jButtonSetAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSetAddMouseClicked
        model = (DefaultTableModel) jTable1.getModel();
        
        String id = jComboBoxSetID.getSelectedItem().toString();
        String item = jComboBoxSetMain.getSelectedItem().toString();
        
        if(!item.equals("-"))
        {
            o1.addOrder(id, "套餐");
            o1.addOrder(item, "套主");

            String [] setmeal = o1.getMeal(o1.getItemCode(id));
            
            if(v.getVoucherId(o1.getItemCode(id)) != -1)
            {
                //有優惠的時候
                model.insertRow(model.getRowCount(),new Object [] {"(套) "+id,item,String.valueOf(v.Calc(v.getVoucherId(o1.getItemCode(id)),o1.getPrice(o1.getItemCode(id)))),""});
            }
            else
            {
                model.insertRow(model.getRowCount(),new Object [] {"(套) "+id,item,setmeal[5],""});
            }
            
            jTable1.setRowHeight(40);//設定行高

            if(!setmeal[2].equals(""))
            {
                model.insertRow(model.getRowCount(),new Object [] {"",o2.getItemName(setmeal[2]),"0",""});
            }
            if(!setmeal[3].equals(""))
            {
                model.insertRow(model.getRowCount(),new Object [] {"",o2.getItemName(setmeal[3]),"0",""});
            }
            if(!setmeal[4].equals(""))
            {
                model.insertRow(model.getRowCount(),new Object [] {"",o2.getItemName(setmeal[4]),"0",""});
            }
        }
    
    }//GEN-LAST:event_jButtonSetAddMouseClicked

    private void jComboBoxSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSingleActionPerformed
       
    }//GEN-LAST:event_jComboBoxSingleActionPerformed

    private void jButtonSingleAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSingleAddMouseClicked
        model = (DefaultTableModel) jTable1.getModel();
        
        String item = jComboBoxSingle.getSelectedItem().toString();
        
        o1.addOrder(item, "單點");
        
        if(v.getVoucherId(o2.getItemCode(item)) != -1)
        {
            model.insertRow(model.getRowCount(),new Object [] {"(單) "+item,"",String.valueOf(v.Calc(v.getVoucherId(o2.getItemCode(item)),o2.getPrice(o2.getItemCode(item)))),""});
        }
        else
        {
            model.insertRow(model.getRowCount(),new Object [] {"(單) "+item,"",String.valueOf(o2.getPrice(o2.getItemCode(item))),""});
        }
        
        jTable1.setRowHeight(40);//設定行高
    }//GEN-LAST:event_jButtonSingleAddMouseClicked

    private void jComboBoxSetMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSetMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSetMainActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainJFrame set = new MainJFrame();
        set.setVisible(true);//把上一頁顯示出來
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubmitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubmitMouseClicked

    private void jButtonDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDelMouseClicked

    private void jButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseClicked
        
        int column = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTable1.getRowHeight();
        
        if(row < jTable1.getRowCount() && row >= 0 && column < jTable1.getColumnCount() && column >= 0 && jTable1.getSelectedRow() != -1)
        {
            Object rowValue = jTable1.getValueAt(row, column);
            DefaultTableModel tableModel = (DefaultTableModel) this.jTable1.getModel();
            
            int selectedRow = jTable1.getSelectedRow();
            
            
        }
    }//GEN-LAST:event_jButtonEditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrderJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonSetAdd;
    private javax.swing.JButton jButtonSingleAdd;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboBoxSetID;
    private javax.swing.JComboBox<String> jComboBoxSetMain;
    private javax.swing.JComboBox<String> jComboBoxSingle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
