/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 109403521
 */
public class MainJFrame extends javax.swing.JFrame
{

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B_Meal = new javax.swing.JButton();
        B_SingleMeal = new javax.swing.JButton();
        B_BreakfastTime = new javax.swing.JButton();
        B_Voucher = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        B_Order = new javax.swing.JButton();
        B_EditOrder = new javax.swing.JButton();
        B_DelOrder = new javax.swing.JButton();
        B_Finish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("歡迎來到第13組的點餐系統");

        B_Meal.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        B_Meal.setText("套餐管理");
        B_Meal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MealActionPerformed(evt);
            }
        });

        B_SingleMeal.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        B_SingleMeal.setText("單點品項管理");
        B_SingleMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SingleMealActionPerformed(evt);
            }
        });

        B_BreakfastTime.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        B_BreakfastTime.setText("早餐時段設定");
        B_BreakfastTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BreakfastTimeActionPerformed(evt);
            }
        });

        B_Voucher.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        B_Voucher.setText("優惠活動設定");
        B_Voucher.setToolTipText("");
        B_Voucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_VoucherActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jLabel2.setText("後台管理");

        jLabel3.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jLabel3.setText("前台作業");

        B_Order.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        B_Order.setText("開始點餐");
        B_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_OrderActionPerformed(evt);
            }
        });

        B_EditOrder.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        B_EditOrder.setText("編輯訂單");
        B_EditOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EditOrderActionPerformed(evt);
            }
        });

        B_DelOrder.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        B_DelOrder.setText("刪除訂單");
        B_DelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DelOrderActionPerformed(evt);
            }
        });

        B_Finish.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        B_Finish.setText("今日營收狀況");
        B_Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_FinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_Order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_EditOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_DelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_Finish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B_SingleMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_BreakfastTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_Meal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_Voucher)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Meal)
                    .addComponent(B_Order))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_SingleMeal)
                    .addComponent(B_EditOrder))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_BreakfastTime)
                    .addComponent(B_DelOrder))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Voucher)
                    .addComponent(B_Finish))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_MealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MealActionPerformed
        SetManageJFrame set = new SetManageJFrame();
        set.setVisible(true);
        this.setVisible(false);//把主選單隱藏起來
    }//GEN-LAST:event_B_MealActionPerformed

    private void B_SingleMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SingleMealActionPerformed
        SingleManageJFrame single = new SingleManageJFrame();
        single.setVisible(true);
        this.setVisible(false);//把主選單隱藏起來
    }//GEN-LAST:event_B_SingleMealActionPerformed

    private void B_BreakfastTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BreakfastTimeActionPerformed
        BreakfastTimeJFrame time = new BreakfastTimeJFrame();
        time.setVisible(true);
        this.setVisible(false);//把主選單隱藏起來
    }//GEN-LAST:event_B_BreakfastTimeActionPerformed

    private void B_VoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_VoucherActionPerformed
        VoucherJFrame voucher = new VoucherJFrame();
        voucher.setVisible(true);
        this.setVisible(false);//把主選單隱藏起來
    }//GEN-LAST:event_B_VoucherActionPerformed

    private void B_OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_OrderActionPerformed
        AddOrderJFrame add = new AddOrderJFrame();
        add.setVisible(true);
        this.setVisible(false);//把主選單隱藏起來
    }//GEN-LAST:event_B_OrderActionPerformed

    private void B_EditOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EditOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_EditOrderActionPerformed

    private void B_DelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DelOrderActionPerformed
        // TODO add your handling  code here:
    }//GEN-LAST:event_B_DelOrderActionPerformed

    private void B_FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_FinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_FinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_BreakfastTime;
    private javax.swing.JButton B_DelOrder;
    private javax.swing.JButton B_EditOrder;
    private javax.swing.JButton B_Finish;
    private javax.swing.JButton B_Meal;
    private javax.swing.JButton B_Order;
    private javax.swing.JButton B_SingleMeal;
    private javax.swing.JButton B_Voucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
